const translation = {
    en: {
        ho: "Home",
        ab: "About",
        sk: "Skills",
        co: "Contact",
        greeting: "Welcome.",
        desc: " Hello! I am a student passionate about web development, AI, and continuous self-improvement in the digital world.",
        text_qu: "Hello World: Where every big journey begins.",
        author_qu: "- A programmer's origin.",
        ab_title:"About Me",
        ab_name:"Hi, I'm <span>Kula!</span>",
        ab_desc1:"I am currently a 11th-grade student at <span>Santiphab high school</span>. At 15 years old, I have developed a deep passion for the world of <span>information technology</span>, with a particular focus on <span>programming.</span>",
        ab_desc2:"Right now, I am dedicated to self-learning <span>Web Development</span> and <span> AI Engineering</span> through various online platforms. My hope is that this small website can serve as a sourceof inspiration for anyone who is also starting their journey in the <span>tech world.</span>",
        ab_thanks:"Lastly, thank you so much for visiting my <span>website!</span>",
        ab_year:"CODING YEAR",
        ab_lang:"LANGUAGE",
        ab_web:"WEBSITE",
        arrow_text:"Hire Me ",
        DownloadCV:"Download CV",
        sk_title:"My Skills",
        role:"Web Developer & AI Enthusiast",
        age:"Age",
        years:"15 Years.",
        edu:"Education",
        school:"Santiphab high school.",
        addr:"Address",
        live:"LPD (Laos).",
        exper:"Experience",
        exper_years:"1+ Year.",
        arrow_text2:"Hire Me ",
        DownloadCV2:"Download CV",
        Skills_title:"Skills",
        Cert_title:"Certificate",
        Project_title:"Project",
        html_css:"Front-end & Design",
        web:"Web Development",
        web_port:"Portfolio & Websites",
        ai:"AI Enthusiast",
        ai_function:"Learning & Exploring",
        ai_tools:"AI Tools",
        Name_cert:"AI Ready ASEAN.",
        Title_cert:"ASEAN Foundation · 2026",
        Name_project:"Project Portfolio",
        Title_project:"A responsive portfolio website showcasing my projects, skills and contact information with a modern and clean design.",
        contact_title:"Contact Me",
        infos_massage:"Feel free to reach out, I'm always open to new ideas and collaborations!.",
        Service:"SERVICE: ONLINE",
        Email_label:"EMAIL ME",
        Whatsapp_chat:"CHAT WHATSAPP",
        Send_message:"SEND MESSAGE",
        ID_name:"Your name",
        ID_email:"Your Email",
        Personal_Transmission_Data:"Write your message here...",
        Submit:"Send Message",
        footer_description:"Turning your ideas and vision into reality through modern code, elegant design and seamless user experiences.",
        quick_links_title:"<span>Quick</span> Links:",
        home_link:"Home",
        about_link:"About",
        skills_link:"Skills",
        contact_link:"Contact",
        startProject:"<span>Start</span> a project with me:",
        footer_project_description:"Have a project in mind? Let's discuss how I can help bring your ideas to life!",
        contact_btn_text:"Contact Me",
        current_text:"2026 Kula. All rights reserved.",
        back_btn:"Back",
        information_personal_web:"collection of web development projects that showcase my skills in creating modern, responsive, and user-friendly websites. Each project reflects my passion for learning, improving my coding abilities, and building real-world solutions with clean and efficient code.",
        tech_used_count:"Technologise Used",
        key_features_count:"Key Features",
        tech_used_title:"Technologies used",
        key_features_title:"Key Features",
        no_link:"No Link",
        feature_responsive:"Responsive Design",
        feature_multilang:"Multi-Language Support",
        feature_contact:"Contact Form",
    },
    th: {
        ho: "หน้าแรก",
        ab: "เกี่ยวกับ",
        sk: "ทักษะ",
        co: "ติดต่อ",
        greeting: "ยินดีต้อนรับ.",
        text_qu: "Hello World: นี่คือจุดเริ่มต้นของทุกการเดินทางที่ยิ่งใหญ่.",
        author_qu: "- จุดเริ่มต้นของโปรแกรมเมอร์.",
        desc: "สวัสดีครับ! ฉันเป็นนักเรียนที่มีความมุ่งมั่นในการเรียนรู้ด้านการพัฒนาเว็บไซต์, Aiและการพัฒนาตนเองในโลกดิจิทัลรวมถึงเทคโนโลยี.",
        ab_title:"เกี่ยวกับฉัน",
        ab_name:"สวัสดีครับ, ฉันชื่อ <span>Kula!</span>",
        ab_desc1:"ปัจจุบัน, ฉันเป็นนักเรียนชั้นมัธยมศึกษาปีที่ 5 ที่ <span>โรงเรียนมัธยมศึกษานติภาพ</span>.ในวัย 15 ปี,ฉันมีความหลงใหลอย่างลึกซึ้งในโลกของ<span>เทค<br>โนโลยีสารสนเทศ</span>, โดยเฉพาะอย่างยิ่งในด้าน <span>การเขียนโปรแกรม.</span>",
        ab_desc2:"ในขณะนี้, ฉันกำลังตั้งใจศึกษาด้วยตนเองเกี่ยวกับการ<span>พัฒนาเว็บไซต์</span>และ<span>(AI)</span> ผ่านแพลตฟอร์มออนไลน์ต่างๆ. ฉันหวังว่าเว็บไซต์เล็กๆแห่งนี้จะสามารถเป็นแหล่งแรงบันดาลใจให้กับใครก็ตามที่กำลังเริ่มต้นเส้นทางใน<span>โลกเทคโนโลยี.</span>",
        ab_thanks:"สุดท้ายนี้, ขอขอบคุณเป็นอย่างสูงที่เข้ามาเยี่ยมชม<span>เว็บไซต์ของฉัน!</span>",
        ab_year:"ปีการเขียนโค้ด",
        ab_lang:"พาสา",
        ab_web:"เว็บไชต์",
        arrow_text:"จ้างฉัน ",
        DownloadCV:"ดาวน์โหลด CV",
        sk_title:"ทักษะของฉัน",
        role:"นักพัฒนาเว็บไซต์ & ผู้ที่ชื่นชอบปัญญาประดิษฐ์",
        age:"อายุ",
        years:"15 ปี.",
        edu:"การศึกษา",
        school:"โรงเรียนสันติภาพ.",
        addr:"ที่อยู่",
        live:"LPD (ลาว).",
        exper:"ประสบการณ์",
        exper_years:"1+ ปี.",
        arrow_text2:"จ้างฉัน ",
        DownloadCV2:"ดาวน์โหลด CV",
        Profile:"ประวัติโดยย่อ",
        Skills_title:"ทักษะ",
        Cert_title:"ใบรับรอง",
        Project_title:"โครงการ",
        html_css:"Front-end & ออกแบบ",
        web:"พัฒนาเว็บไซต์",
        web_port:"ผลงาน & เว็บไซต์",
        ai:"ผู้ที่ชื่นชอบปัญญาประดิษฐ์",
        ai_function:"การเรียนรู้ & การสำรวจ",
        ai_tools:"เครื่องมือ AI",
        Name_cert:"AI Ready ASEAN.",
        Title_cert:"มูลนิธิอาเซียน · 2026",
        Name_project:"Project Portfolio",
        Title_project:"portfolio website ผลงานที่ตอบสนองได้ดีแสดงโครงการ,ทักษะและข้อมูลการติดต่อของฉันด้วยการออกแบบที่ทันสมัยและสะอาดตา.",
        contact_title:"ติดต่อฉัน",
        infos_massage:"อย่าลังเลที่จะติดต่อมา, ฉันเปิดรับไอเดียและความร่วมมือใหม่ๆเสมอ!",
        direct_contact:"ติดต่อโดยตรง",
        Send_message:"ส่งข้อความ",
        Service:"บริการ: ออนไลน์",
        Email_label:"ส่งEmailถึงฉัน",
        Whatsapp_chat:"แชท WhatsApp",
        Send_message:"ส่งข้อความ",
        ID_name:"ชื่อของคุณ",
        ID_email:"อีเมลของคุณ",
        Personal_Transmission_Data:"เขียนข้อความของคุณที่นี่...",
        Submit:"ส่งข้อความ",
        footer_description:"เปลี่ยนไอเดียและวิสัยทัศน์ของคุณให้เป็นจริงผ่านโค้ดที่ทันสมัย, การออกแบบที่สง่างามและประสบการณ์ผู้ใช้งานที่ราบรื่น.",
        quick_links_title:"<span>ลิงค์</span>ด่วน:",
        home_link:"หน้าแรก",
        about_link:"เกี่ยวกับ",
        skills_link:"ทักษะ",
        contact_link:"ติดต่อ",
        startProject:"<span>เริ่ม</span>โปรเจคกับฉัน:",
        footer_project_description:"มีโปรเจคในใจไหม? มาคุยกันเถอะว่าฉันจะช่วยทำให้ไอเดียของคุณเป็นจริงได้อย่างไร!",
        contact_btn_text:"ติดต่อฉัน",
        current_text:"2026 Kula. สงวนลิขสิทธิ์.",
        back_btn:"ย้อนกลับ",
        information_personal_web:"รวมผลงานพัฒนาเว็บไซต์ที่แสดงให้เห็นถึงทักษะของผมในการสร้างเว็บไซต์ที่ทันสมัย,​ตอบสนองต่อทุกอุปกรณ์และใช้งานง่าย.แต่ละโปรเจกต์สะท้อนให้เห็นถึงความมุ่งมั่นของผมในการเรียนรู้,พัฒนาทักษะการเขียนโค้ดและสร้างโซลูชันที่ใช้งานได้จริงด้วยโค้ดที่สะอาดและมีประสิทธิภาพ",
        tech_used_count:"เทคโนโลยีที่ใช้",
        key_features_count:"คุณสมบัติเด่น",
        tech_used_title:"เทคโนโลยีที่ใช้",
        key_features_title:"คุณสมบัติเด่น",
        no_link:"ไม่มีลิงก์",
        feature_responsive:"ดีไซน์ตอบสนองทุกอุปกรณ์",
        feature_multilang:"รองรับหลายภาษา",
        feature_contact:"แบบฟอร์มติดต่อ",
    },
    la: {
        ho: "ໜ້າຫຼັກ",
        ab: "ກ່ຽວກັບ",
        sk: "ທັກສະ",
        co: "ຕິດຕໍ່",
        text_qu: "Hello World: ນີ້ແມ່ນຈຸດເລີ່ມຕົ້ນຂອງທູກໆການເດີນທາງຍິ່ງໃຫຍ່.",
        author_qu: "- ຈຸດເລີ່ມຕົ້ນຂອງໂປຣແກຣມເມີ.",
        greeting: "ຍິນດີຕ້ອນຮັບ.",
        desc: "ສະບາຍດີ! ຂ້ອຍແມ່ນນັກຮຽນຄົນໜື່ງທີ່ມາພ້ອມກັບຄວາມມັກໃນການຮຽນຮູ້ດ້ານການພັດທະນາເວັບໄຊ, Aiແລະການພັດທະນາຕົນເອງໃນໂລກດີຈິຕອນ.",
        ab_title:"ກ່ຽວກັບຂ້ອຍ",
        ab_name:"ສະບາຍດີ, ຂ້ອຍຊື່ <span>Kula!</span>",
        ab_desc1:"ປະຈຸບັນ, ຂ້ອຍປັນນັກຮຽນຊັ້ນມັດທະຍົມສຶກສາປີທີ 5 ຢູ່ <span>ໂຮງຮຽນມັດທະຍົມສຶກສາສັນຕິພາບ</span>. ໃນອາຍຸ 15 ປີ, ຂ້ອຍໄດ້ມີຄວາມມັກຮັກຢ່າງເລິກເຊິ່ງຕໍ່ກັບໂລກຂອງ<span>ເຕັກໂນໂລຊີ ຂໍ້ມູນຂ່າວສານ</span>, ໂດຍເນັ້ນໃສ່ເປັນພິເສດກ່ຽວກັບ <span>ການຂຽນໂປຣແກຣມ.</span>",
        ab_desc2:"ໃນເວລານີ້, ຂ້ອຍກໍາລັງຕັ້ງໃຈສຶກສາດ້ວຍຕົນເອງກ່ຽວກັບ <span>ການພັດທະນາເວັບໄຊ</span>ແລະ<span>ວິສະວະກຳປັນຍາປະດິດ (AI)</span> ຜ່ານເວທີອອນລາຍຕ່າງໆ.ຂ້ອຍຫວັງxວ່າເວັບໄຊນ້ອຍໆແຫ່ງນີ້ຈະສາມາດເປັນແຫຼ່ງແຮງບັນດານໃຈໃຫ້ກັບທຸກຄົນທີ່ກໍາລັງເລີ່ມຕົ້ນເສັ້ນທາງໃນ<span>ໂລກເຕັກໂນໂລຊີ.</span>",
        ab_thanks:"ສຸດທ້າຍນີ້, ຂອບໃຈຫຼາຍໆທີ່ເຂົ້າມາຢ້ຽມຊົມ <span>ເວັບໄຊຂອງຂ້ອຍ!</span>",
        ab_year:"ປີການຂຽນໂຄ້ດ",
        ab_lang:"ພາສາ",
        ab_web:"ເວັບໄຊ",
        arrow_text:"ຈ້າງຂ້ອຍ ",
        DownloadCV:"ດາວໂຫຼດ CV",
        sk_title:"ທັກສະຂອງຂ້ອຍ",
        role:"ນັກພັດທະນາເວັບໄຊ & ຜູ້ທີ່ມັກຮັກປັນຍາປະດິດ",
        age:"ອາຍູ",
        years:"15 ປີ.",
        edu:"ການສືກສາ",
        school:"ໂຮງຮຽນສັນຕິພາບ.",
        addr:"ທີ່ຢູ່",
        live:"LPD (ລາວ).",
        exper:"ປະສົບການ",
        exper_years:"1+ ປີ.",
        arrow_text2:"ຈ້າງຂ້ອຍ ",
        DownloadCV2:"ດາວໂຫຼດ CV",
        Profile:"ໂປຣໄຟລ໌",
        Skills_title:"ທັກສະ",
        Cert_title:"ໃບຢັ້ງຢືນ",
        Project_title:"ໂຄງການ",
        html_css:"Front-end & ອອກແບບ",
        web:"ພັດທະນາເວັບໄຊທ໌",
        web_port:"Portfolio & ເວັບໄຊທ໌",
        ai:"ຜູ້ທີ່ມັກຮັກປັນຍາປະດິດ",
        ai_function:"ການຮຽນຮູ້ & ການສຳຫຼວດ",
        ai_tools:"ເຄື່ອງ​ມື AI",
        Name_cert:"AI Ready ASEAN.",
        Title_cert:"ມູນນິທິອາຊຽນ · 2026",
        Name_project:"Project Portfolio",
        Title_project:"portfolio website ທີ່ຕອບສະໜອງສະແດງໂຄງການ,ທັກສະແລະຂໍ້ມູນຕິດຕໍ່ຂອງຂ້ອຍດ້ວຍການອອກແບບທັນສະໄໝແລະສະອາດ.",
        contact_title:"ຕິດຕໍ່ຂ້ອຍ",
        infos_massage:"ຢ່າລັງເລ່ທີ່ຈະຕິດຕໍ່ມາ, ຂ້ອຍເປີດຮັບໄອເດຍແລະການຮຽນຮູ້ໃໝ່ໆສະເໝີ!",
        direct_contact:"ຕິດຕໍ່ໂດຍກົງ",
        Send_message:"ສົ່ງຂໍ້ຄວາມ",
        Service:"ບໍລິການ: ອອນໄລ",
        Email_label:"ສົ່ງEmailເຖີງຂ້ອຍ",
        Whatsapp_chat:"ແຊທ WhatsApp",
        Send_message:"ສົ່ງຂໍ້ຄວາມ",
        ID_name:"ຊື່ຂອງທ່ານ",
        ID_email:"ອີເມວຂອງທ່ານ",
        Personal_Transmission_Data:"ຂຽນຂໍ້ຄວາມຂອງທ່ານຢູ່ບ່ອນນີ້...",
        Submit:"ສົ່ງຂໍ້ຄວາມ",
        footer_description:"ປ່ຽນໄອເດຍແລະວິສັດທັດຂອງທ່ານໃຫ້ເປັນຈິງຜ່ານ<br>ໂຄ້ດທີ່ທັນສະໄໝ, ການອອກແບບທີ່ສະດວກແລະປະສົບການຜູ້ໃຊ້ງານຢ່າງລຽບງ່າຍ.",
        quick_links_title:"<span>ລິ້ງ</span>ດ່ວນ:",
        home_link:"ໜ້າຫຼັກ",
        about_link:"ກ່ຽວກັບ",
        skills_link:"ທັກສະ",
        contact_link:"ຕິດຕໍ່",
        startProject:"<span>ເລີ່ມ</span>ໂປເຈັກກັບຂ້ອຍ:",
        footer_project_description:"ມີໂປເຈັກໃນໃຈບໍ່? ມາຄຸຍກັນນະວ່າຂ້ອຍຈະຊ່ວຍເຮັດໃຫ້ໄອເດຍຂອງເຈົ້າເປັນຈິງໄດ້ແນວໃດ!",
        contact_btn_text:"ຕິດຕໍ່ຂ້ອຍ",
        current_text:"2026 Kula. ສະຫງວນລິຂະສິດ.",
        back_btn:"ກັບຄືນ",
        information_personal_web:"ຊຸດໂຄງການພັດທະນາເວັບໄຊທ໌ທີ່ສະແດງໃຫ້ເຫັນທັກສະຂອງຂ້ອຍໃນ<br>ການສ້າງເວັບໄຊທ໌ທີ່ທັນສະໄໝ,ຕອບສະໜອງໄດ້ດີແລະເປັນມິດກັບຜູ້ໃຊ້.ແຕ່ລະໂຄງການສະທ້ອນໃຫ້ເຫັນເຖິງຄວາມມັກຂອງຂ້ອຍໃນການຮຽນຮູ້,ການປັບປຸງຄວາມສາມາດໃນການຂຽນໂປຣແກຣມຂອງຂ້ອຍແລະ<br>ການສ້າງວິທີແກ້ໄຂໃນໂລກແຫ່ງຄວາມເປັນຈິງດ້ວຍລະຫັດທີ່ສະອາດ ແລະ ມີປະສິດທິພາບ.",
        tech_used_count:"ເຕັກໂນໂລຊີທີ່ໃຊ້",
        key_features_count:"ຄຸນສົມບັດເດັ່ນ",
        tech_used_title:"ເຕັກໂນໂລຊີທີ່ໃຊ້",
        key_features_title:"ຄຸນສົມບັດເດັ່ນ",
        no_link:"ບໍ່ມີລິ້ງ",
        feature_responsive:"ດີໄຊທ໌ຕອບສະໜອງທຸກອຸປະກອນ",
        feature_multilang:"ຮອງຮັບຫຼາຍພາສາ",
        feature_contact:"ແບບຟອມຕິດຕໍ່",
    }
};

function changeLang(lang) {
    currentLang = lang;
    localStorage.setItem("kula_lang", lang);
    document.body.style.animation = "none";

    setTimeout(() => {
        applyTranslation(lang);
        document.body.style.animation = "unblur 2s ease-in-out forwards";
        startTypewriters(lang);
    }, 50);
}

function applyTranslation(lang) {
    const t = translation[lang];
    if (!t) return;

    // ແປ text ທົ່ວໄປ
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.dataset.i18n;
        if (t[key] !== undefined) {
            el.innerHTML = t[key];
        }
    });

    // ແປ placeholder (ຊ່ອງ input)
    document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
        const key = el.dataset.i18nPlaceholder;
        if (t[key] !== undefined) {
            el.placeholder = t[key];
        }
    });
}

document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("kula_lang") || "en";
    currentLang = savedLang;

    const langSelect = document.getElementById("LangSelect");
    if (langSelect) {
        langSelect.value = savedLang;
    }

    applyTranslation(savedLang);
    if (typeof startTypewriters === "function") {
        startTypewriters(savedLang);
    }
});
